/**
 * This class is generated by jOOQ
 */
package dk.magenta.eark.erms.db.connector.tables;


import dk.magenta.eark.erms.db.connector.Exm;
import dk.magenta.eark.erms.db.connector.Keys;
import dk.magenta.eark.erms.db.connector.tables.records.ProfilesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profiles extends TableImpl<ProfilesRecord> {

    private static final long serialVersionUID = 375849723;

    /**
     * The reference instance of <code>exm.profiles</code>
     */
    public static final Profiles PROFILES = new Profiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfilesRecord> getRecordType() {
        return ProfilesRecord.class;
    }

    /**
     * The column <code>exm.profiles.id</code>.
     */
    public final TableField<ProfilesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>exm.profiles.name</code>.
     */
    public final TableField<ProfilesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>exm.profiles.username</code>.
     */
    public final TableField<ProfilesRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR.length(32).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>exm.profiles</code> table reference
     */
    public Profiles() {
        this("profiles", null);
    }

    /**
     * Create an aliased <code>exm.profiles</code> table reference
     */
    public Profiles(String alias) {
        this(alias, PROFILES);
    }

    private Profiles(String alias, Table<ProfilesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Profiles(String alias, Table<ProfilesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Exm.EXM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProfilesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_PROFILES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProfilesRecord> getPrimaryKey() {
        return Keys.KEY_PROFILES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProfilesRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfilesRecord>>asList(Keys.KEY_PROFILES_PRIMARY, Keys.KEY_PROFILES_UNIQUE_INDEX);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Profiles as(String alias) {
        return new Profiles(alias, this);
    }

    /**
     * Rename this table
     */
    public Profiles rename(String name) {
        return new Profiles(name, null);
    }
}
