/**
 * This class is generated by jOOQ
 */
package dk.magenta.eark.erms.db.connector.tables;


import dk.magenta.eark.erms.db.connector.Exm;
import dk.magenta.eark.erms.db.connector.Keys;
import dk.magenta.eark.erms.db.connector.tables.records.ProfilesRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Profiles extends TableImpl<ProfilesRecord> {

    private static final long serialVersionUID = 578407660;

    /**
     * The reference instance of <code>exm.Profiles</code>
     */
    public static final Profiles PROFILES = new Profiles();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProfilesRecord> getRecordType() {
        return ProfilesRecord.class;
    }

    /**
     * The column <code>exm.Profiles.profileName</code>.
     */
    public final TableField<ProfilesRecord, String> PROFILENAME = createField("profileName", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

    /**
     * The column <code>exm.Profiles.url</code>.
     */
    public final TableField<ProfilesRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>exm.Profiles.userName</code>.
     */
    public final TableField<ProfilesRecord, String> USERNAME = createField("userName", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>exm.Profiles.password</code>.
     */
    public final TableField<ProfilesRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>exm.Profiles</code> table reference
     */
    public Profiles() {
        this("Profiles", null);
    }

    /**
     * Create an aliased <code>exm.Profiles</code> table reference
     */
    public Profiles(String alias) {
        this(alias, PROFILES);
    }

    private Profiles(String alias, Table<ProfilesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Profiles(String alias, Table<ProfilesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Exm.EXM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProfilesRecord> getPrimaryKey() {
        return Keys.KEY_PROFILES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProfilesRecord>> getKeys() {
        return Arrays.<UniqueKey<ProfilesRecord>>asList(Keys.KEY_PROFILES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Profiles as(String alias) {
        return new Profiles(alias, this);
    }

    /**
     * Rename this table
     */
    public Profiles rename(String name) {
        return new Profiles(name, null);
    }
}
