/**
 * This class is generated by jOOQ
 */
package dk.magenta.eark.erms.db.connector;


import dk.magenta.eark.erms.db.connector.tables.Profiles;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Exm extends SchemaImpl {

    private static final long serialVersionUID = 140681626;

    /**
     * The reference instance of <code>exm</code>
     */
    public static final Exm EXM = new Exm();

    /**
     * The table <code>exm.Profiles</code>.
     */
    public final Profiles PROFILES = dk.magenta.eark.erms.db.connector.tables.Profiles.PROFILES;

    /**
     * No further instances allowed
     */
    private Exm() {
        super("exm", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Profiles.PROFILES);
    }
}
