/**
 * This class is generated by jOOQ
 */
package dk.magenta.eark.erms.db.connector;


import dk.magenta.eark.erms.db.connector.tables.Person;
import dk.magenta.eark.erms.db.connector.tables.Profiles;
import dk.magenta.eark.erms.db.connector.tables.Repositories;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in exm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exm.person</code>.
     */
    public static final Person PERSON = dk.magenta.eark.erms.db.connector.tables.Person.PERSON;

    /**
     * The table <code>exm.profiles</code>.
     */
    public static final Profiles PROFILES = dk.magenta.eark.erms.db.connector.tables.Profiles.PROFILES;

    /**
     * The table <code>exm.repositories</code>.
     */
    public static final Repositories REPOSITORIES = dk.magenta.eark.erms.db.connector.tables.Repositories.REPOSITORIES;
}
