/**
 * This class is generated by jOOQ
 */
package dk.magenta.eark.erms.db.connector;


import dk.magenta.eark.erms.db.connector.tables.Profiles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in exm
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exm.Profiles</code>.
     */
    public static final Profiles PROFILES = dk.magenta.eark.erms.db.connector.tables.Profiles.PROFILES;
}
