
package org.apache.chemistry.opencmis.commons.impl.jaxb;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-08-15T08:42:24.692+03:00
 * Generated source version: 3.0.9
 */

@WebFault(name = "cmisFault", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
public class CmisException extends Exception {
    
    private org.apache.chemistry.opencmis.commons.impl.jaxb.CmisFaultType cmisFault;

    public CmisException() {
        super();
    }
    
    public CmisException(String message) {
        super(message);
    }
    
    public CmisException(String message, Throwable cause) {
        super(message, cause);
    }

    public CmisException(String message, org.apache.chemistry.opencmis.commons.impl.jaxb.CmisFaultType cmisFault) {
        super(message);
        this.cmisFault = cmisFault;
    }

    public CmisException(String message, org.apache.chemistry.opencmis.commons.impl.jaxb.CmisFaultType cmisFault, Throwable cause) {
        super(message, cause);
        this.cmisFault = cmisFault;
    }

    public org.apache.chemistry.opencmis.commons.impl.jaxb.CmisFaultType getFaultInfo() {
        return this.cmisFault;
    }
}
