package org.apache.chemistry.opencmis.commons.impl.jaxb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.9
 * 2016-08-15T08:42:24.781+03:00
 * Generated source version: 3.0.9
 * 
 */
@WebServiceClient(name = "RepositoryService", 
                  wsdlLocation = "file:/C:/Dev/tmp/chemistry-opencmis-0.14.0-source-release/chemistry-opencmis-0.14.0/chemistry-opencmis-commons/chemistry-opencmis-commons-impl/src/main/resources/wsdl/cmis11/CMISWS-Service.wsdl",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/") 
public class RepositoryService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RepositoryService");
    public final static QName RepositoryServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "RepositoryServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Dev/tmp/chemistry-opencmis-0.14.0-source-release/chemistry-opencmis-0.14.0/chemistry-opencmis-commons/chemistry-opencmis-commons-impl/src/main/resources/wsdl/cmis11/CMISWS-Service.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RepositoryService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Dev/tmp/chemistry-opencmis-0.14.0-source-release/chemistry-opencmis-0.14.0/chemistry-opencmis-commons/chemistry-opencmis-commons-impl/src/main/resources/wsdl/cmis11/CMISWS-Service.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RepositoryService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RepositoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RepositoryService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RepositoryService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RepositoryService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public RepositoryService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns RepositoryServicePort
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryServicePort getRepositoryServicePort() {
        return super.getPort(RepositoryServicePort, RepositoryServicePort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RepositoryServicePort
     */
    @WebEndpoint(name = "RepositoryServicePort")
    public RepositoryServicePort getRepositoryServicePort(WebServiceFeature... features) {
        return super.getPort(RepositoryServicePort, RepositoryServicePort.class, features);
    }

}
